use anyhow::Result;
use prost::Message;
use tako::Method;
use tako::grpc::GrpcRequest;
use tako::grpc::GrpcResponse;
use tako::grpc::GrpcStatusCode;
use tako::router::Router;

// In a real project, these would be generated by prost-build from a .proto file.
// Here we define them manually for the example.

#[derive(Clone, PartialEq, Message)]
pub struct HelloRequest {
  #[prost(string, tag = "1")]
  pub name: String,
}

#[derive(Clone, PartialEq, Message)]
pub struct HelloReply {
  #[prost(string, tag = "1")]
  pub message: String,
}

#[derive(Clone, PartialEq, Message)]
pub struct EchoRequest {
  #[prost(bytes = "vec", tag = "1")]
  pub data: Vec<u8>,
}

#[derive(Clone, PartialEq, Message)]
pub struct EchoReply {
  #[prost(bytes = "vec", tag = "1")]
  pub data: Vec<u8>,
  #[prost(uint32, tag = "2")]
  pub size: u32,
}

async fn say_hello(req: GrpcRequest<HelloRequest>) -> GrpcResponse<HelloReply> {
  let name = &req.message.name;

  if name.is_empty() {
    return GrpcResponse::error(GrpcStatusCode::InvalidArgument, "name must not be empty");
  }

  GrpcResponse::ok(HelloReply {
    message: format!("Hello, {name}!"),
  })
}

async fn echo(req: GrpcRequest<EchoRequest>) -> GrpcResponse<EchoReply> {
  let data = req.message.data;
  let size = data.len() as u32;
  GrpcResponse::ok(EchoReply { data, size })
}

#[tokio::main]
async fn main() -> Result<()> {
  tracing_subscriber::fmt::init();

  let mut router = Router::new();

  // Register gRPC handlers as standard POST routes
  router.route(Method::POST, "/grpc.Greeter/SayHello", say_hello);
  router.route(Method::POST, "/grpc.Echo/Echo", echo);

  let listener = tokio::net::TcpListener::bind("127.0.0.1:8080").await?;

  println!("gRPC server on http://127.0.0.1:8080");
  println!("Registered services:");
  println!("  POST /grpc.Greeter/SayHello");
  println!("  POST /grpc.Echo/Echo");
  println!();
  println!("Use grpcurl or a gRPC client to test.");

  tako::serve(listener, router).await;

  Ok(())
}
